.TH "CREDITS\-LOG" "1" "February 2025" "1.0.10"
.SH "NAME"
\fBCREDITS-LOG\fR \- credits\-log It is a tool to display authors and contributors in the browser console\.
.SH Synopsis
.P
It is a tool to display authors and contributors
.br
in the browser console\. They are automatically added at the time of
.br
when compiling your project\.
.P
The package contains a CLI tool to be able to add, edit, or delete content to the package\.json that will be
.br
remove content to the package\.json that will eventually be injected into the same project\.
.br
same project\.
.SH See also
.P
.UR https://github.com/klich3/credits-log
.I Git Repository
.UE

